------------------------------------------------------------------
--  Permutation Groups in Ada SPARK                              --
--  Implementation of Donald E. Knuth's algorithms Aₖ(π) and Bₖ(π) --
--  for computing strong generators and transversal systems        --
--                                                               --
--  File: permutations.adb                                        --
--  Description: Complete implementation with all algorithms       --
--  Version: 0.01                                               --
--                                                               --
--  Author: Vibe Code Agent                                       --
--  Date: 2024                                                   --
--  Reference: Knuth, D.E. "The Art of Computer Programming"     --
--             Volume 2, Section 4.6.3                            --
------------------------------------------------------------------

package body Permutations is
   pragma SPARK_Mode (On);

   -- Identity permutation
   function Identity return Permutation is
   begin
      return Result : Permutation do
         for I in Index loop
            Result(I) := I;
         end loop;
      end return;
   end Identity;

   -- Permutation multiplication (composition)
   function Multiply (Left, Right : Permutation) return Permutation is
   begin
      return Result : Permutation do
         for I in Index loop
            Result(I) := Left(Right(I));
         end loop;
      end return;
   end Multiply;

   -- Permutation inverse
   function Inverse (P : Permutation) return Permutation is
   begin
      return Result : Permutation do
         for I in Index loop
            Result(P(I)) := I;
         end loop;
      end return;
   end Inverse;

   -- Check if a permutation is the identity
   function Is_Identity (P : Permutation) return Boolean is
   begin
      for I in Index loop
         if P(I) /= I then
            return False;
         end if;
      end loop;
      return True;
   end Is_Identity;

   -- Check if permutation Pi is a member of the group generated by Sigma up to level K
   function Is_Member (Pi : Permutation; K : Index; Sigma : Sigma_Type) return Boolean is
   begin
      if K = 1 then
         return True;
      end if;
      
      declare
         J : Index := Pi(K);
      begin
         -- If σₖⱼ is empty, Pi is not in the group
         if Sigma(K, J).Length = 0 then
            return False;
         end if;
         
         -- If K = 1, we're done (base case)
         if K = 1 then
            return True;
         end if;
         
         -- Recursively check if Pi * σₖⱼ⁻¹ is in Γ(k-1)
         declare
            Sigma_KJ : Permutation := Sigma(K, J).Element(1).all;
            Sigma_KJ_Inv : Permutation := Inverse(Sigma_KJ);
            Pi_Transformed : Permutation := Multiply(Pi, Sigma_KJ_Inv);
         begin
            return Is_Member(Pi_Transformed, K-1, Sigma);
         end;
      end;
   end Is_Member;

   -- Algorithm Aₖ(π): Appends a new permutation π to T(k)
   procedure Algorithm_A (K : Index; Pi : Permutation;
                         Sigma : in out Sigma_Type;
                         T : in out T_Type) is
   begin
      -- Add Pi to T(K)
      T(K).Append(new Permutation'(Pi));
      
      -- If K = 1, we're done (base case)
      if K = 1 then
         return;
      end if;
      
      -- For all σ ∈ Σ(k) and τ ∈ T(k), check if στ is not already in Γ(k)
      for J in Index loop
         if Sigma(K, J).Length > 0 then
            declare
               Sigma_KJ : Permutation := Sigma(K, J).Element(1).all;
            begin
               -- For each τ in T(K)
               for Tau_Idx in 1 .. T(K).Length loop
                  declare
                     Tau : Permutation := T(K).Element(Tau_Idx).all;
                     Product : Permutation := Multiply(Sigma_KJ, Tau);
                  begin
                     -- Check if Product is not already in Γ(k)
                     if not Is_Member(Product, K, Sigma) then
                        -- Call Algorithm_B for this product
                        Algorithm_B(K, Product, Sigma, T);
                     end if;
                  end;
               end loop;
            end;
         end if;
      end loop;
      
      -- Also check products with the new Pi
      for Tau_Idx in 1 .. T(K).Length loop
         declare
            Tau : Permutation := T(K).Element(Tau_Idx).all;
            Product1 : Permutation := Multiply(Pi, Tau);
            Product2 : Permutation := Multiply(Tau, Pi);
         begin
            if not Is_Member(Product1, K, Sigma) then
               Algorithm_B(K, Product1, Sigma, T);
            end if;
            if not Is_Member(Product2, K, Sigma) then
               Algorithm_B(K, Product2, Sigma, T);
            end if;
         end;
      end loop;
   end Algorithm_A;

   -- Algorithm Bₖ(π): Ensures π is in Γ(k)
   procedure Algorithm_B (K : Index; Pi : Permutation;
                         Sigma : in out Sigma_Type;
                         T : in out T_Type) is
   begin
      -- Let π map k ↦ j
      declare
         J : Index := Pi(K);
      begin
         -- If σₖⱼ is empty, set σₖⱼ ← π and terminate
         if Sigma(K, J).Length = 0 then
            Sigma(K, J).Append(new Permutation'(Pi));
            return;
         end if;
         
         -- If k = 1, we're done (base case)
         if K = 1 then
            return;
         end if;
         
         -- Check if πσₖⱼ⁻¹ ∈ Γ(k-1)
         declare
            Sigma_KJ : Permutation := Sigma(K, J).Element(1).all;
            Sigma_KJ_Inv : Permutation := Inverse(Sigma_KJ);
            Pi_Transformed : Permutation := Multiply(Pi, Sigma_KJ_Inv);
         begin
            if Is_Member(Pi_Transformed, K-1, Sigma) then
               return; -- π is already in Γ(k), terminate
            else
               -- Otherwise, call Algorithm Aₖ₋₁(πσₖⱼ⁻¹)
               Algorithm_A(K-1, Pi_Transformed, Sigma, T);
               
               -- After adding new generators, we may need to update σₖⱼ
               if not Is_Member(Pi, K, Sigma) then
                  Sigma(K, J).Clear;
                  Sigma(K, J).Append(new Permutation'(Pi));
               end if;
            end if;
         end;
      end;
   end Algorithm_B;

   -- Initialize the data structures for a given group size N
   procedure Initialize (N : Index; Sigma : out Sigma_Type; T : out T_Type) is
   begin
      -- Initialize all T(k) to empty vectors
      for K in Index loop
         T(K).Clear;
      end loop;
      
      -- Initialize all σₖⱼ to empty vectors
      for K in Index loop
         for J in Index loop
            Sigma(K, J).Clear;
         end loop;
      end loop;
   end Initialize;

   -- Add a new generator to the group
   procedure Add_Generator (Pi : Permutation; Sigma : in out Sigma_Type; T : in out T_Type) is
   begin
      -- Start with the highest level (Index'Last)
      Algorithm_B(Index'Last, Pi, Sigma, T);
   end Add_Generator;

   -- Compute the strong generating set for a given set of generators
   procedure Compute_Strong_Generators (Generators : Perm_Vector;
                                        Sigma : out Sigma_Type;
                                        T : out T_Type) is
   begin
      -- Initialize the data structures
      Initialize(Index'Last, Sigma, T);
      
      -- Add each generator to the group
      for I in 1 .. Generators.Length loop
         Add_Generator(Generators.Element(I).all, Sigma, T);
      end loop;
   end Compute_Strong_Generators;

   -- Create a transposition (swap of two elements)
   function Create_Transposition (I, J : Index) return Permutation is
   begin
      return Result : Permutation := Identity do
         Result(I) := J;
         Result(J) := I;
      end return;
   end Create_Transposition;

   -- Create a cycle permutation
   function Create_Cycle (Elements : array (Positive range <>) of Index) return Permutation is
   begin
      return Result : Permutation := Identity do
         -- Create the cycle: Elements(1) -> Elements(2) -> ... -> Elements(N) -> Elements(1)
         for K in Elements'First .. Elements'Last - 1 loop
            Result(Elements(K)) := Elements(K + 1);
         end loop;
         Result(Elements(Elements'Last)) := Elements(Elements'First);
      end return;
   end Create_Cycle;

   -- Check if two permutations are equal
   function "=" (Left, Right : Permutation) return Boolean is
   begin
      for I in Index loop
         if Left(I) /= Right(I) then
            return False;
         end if;
      end loop;
      return True;
   end "=";

end Permutations;
