------------------------------------------------------------------
--  Permutation Groups in Ada SPARK                              --
--  Implementation of Donald E. Knuth's algorithms Aₖ(π) and Bₖ(π) --
--  for computing strong generators and transversal systems        --
--                                                               --
--  File: permutations.ads                                        --
--  Description: Complete implementation with all algorithms       --
--  Version: 0.09                                               --
--                                                               --
--  Author: Vibe Code Agent                                       --
--  Date: 2024                                                   --
--  Reference: Knuth, D.E. "The Art of Computer Programming"     --
--             Volume 2, Section 4.6.3                            --
------------------------------------------------------------------

package Permutations is
   pragma SPARK_Mode (On);

   -- Maximum size for permutations
   Max_Size : constant Positive := 100;

   -- Maximum number of elements in any vector
   Max_Vector_Size : constant Positive := 1000;

   -- Index type for permutations
   type Index is new Positive range 1 .. Max_Size;

   -- Permutation type: maps Index to Index
   type Permutation is array (Index) of Index;

   -- Identity permutation
   function Identity return Permutation
     with SPARK_Mode => On,
          Pre => True,
          Post => (for all I in Index => Identity'Result(I) = I);

   -- Permutation multiplication (composition): Left * Right
   function Multiply (Left, Right : Permutation) return Permutation
     with SPARK_Mode => On,
          Pre => (for all I in Index => Left(I) in Index and Right(I) in Index);

   -- Permutation inverse
   function Inverse (P : Permutation) return Permutation
     with SPARK_Mode => On,
          Pre => True;

   -- Check if a permutation is the identity
   function Is_Identity (P : Permutation) return Boolean
     with SPARK_Mode => On,
          Pre => True;

   -- SPARK-compatible Vector type for storing permutations
   type Vector_Index is range 1 .. Max_Vector_Size;
   type Vector_Capacity is range 0 .. Max_Vector_Size;
   
   type Permutation_Array is array (Vector_Index) of Permutation;
   
   type Permutation_Vector is record
      Length : Vector_Capacity := 0;
      Data : Permutation_Array;
   end record;

   -- Sigma type: array of vectors for each k and j
   type Sigma_Type is array (Index, Index) of Permutation_Vector;

   -- T type: array of vectors for strong generators at each level k
   type T_Type is array (Index) of Permutation_Vector;

   -- Check if permutation Pi is a member of the group generated by Sigma up to level K
   function Is_Member (Pi : Permutation; K : Index; Sigma : Sigma_Type) return Boolean
     with SPARK_Mode => On,
          Pre => K in Index and Pi'Length = Max_Size,
          Subprogram_Variant => (Decreases => K);

   -- Algorithm Aₖ(π): Appends a new permutation π to T(k)
   procedure Algorithm_A (K : Index; Pi : Permutation;
                         Sigma : in out Sigma_Type;
                         T : in out T_Type)
     with SPARK_Mode => On,
          Pre => K in Index and Pi'Length = Max_Size;

   -- Algorithm Bₖ(π): Ensures π is in Γ(k)
   procedure Algorithm_B (K : Index; Pi : Permutation;
                         Sigma : in out Sigma_Type;
                         T : in out T_Type)
     with SPARK_Mode => On,
          Pre => K > 1 and Pi'Length = Max_Size;

   -- Initialize the data structures
   procedure Initialize (N : Index; Sigma : out Sigma_Type; T : out T_Type)
     with SPARK_Mode => On,
          Pre => N in Index,
          Post => (for all K in Index => Vector_Length(T(K)) = 0) and
                  (for all K in Index => (for all J in Index => Vector_Length(Sigma(K, J)) = 0));

   -- Add a new generator to the group
   procedure Add_Generator (Pi : Permutation; Sigma : in out Sigma_Type; T : in out T_Type)
     with SPARK_Mode => On,
          Pre => Pi'Length = Max_Size;

   -- Compute the strong generating set for a given set of generators
   type Generator_Array is array (Positive range <>) of Permutation;
   
   procedure Compute_Strong_Generators (Generators : Generator_Array;
                                        Sigma : out Sigma_Type;
                                        T : out T_Type)
     with SPARK_Mode => On,
          Pre => Generators'Length <= Max_Vector_Size and
                (for all I in Generators'Range => Generators(I)'Length = Max_Size);

   -- Create a transposition (swap of two elements)
   function Create_Transposition (I, J : Index) return Permutation
     with SPARK_Mode => On,
          Pre => I in Index and J in Index;

   -- Maximum number of elements for cycle creation
   Max_Cycle_Size : constant Positive := Max_Size;
   
   -- Type for cycle elements
   type Cycle_Elements is array (Positive range 1 .. Max_Cycle_Size) of Index;
   
   -- Create a cycle permutation
   function Create_Cycle (Elements : Cycle_Elements; Length : Positive) return Permutation
     with SPARK_Mode => On,
          Pre => Length >= 2 and Length <= Max_Cycle_Size and
                (for all I in 1 .. Length => Elements(I) in Index);

   -- Check if two permutations are equal
   function "=" (Left, Right : Permutation) return Boolean
     with SPARK_Mode => On,
          Pre => True;

   -- Helper function to get the length of a Permutation_Vector
   function Vector_Length (V : Permutation_Vector) return Vector_Capacity;

   -- Helper procedure to append to a Permutation_Vector
   procedure Vector_Append (V : in out Permutation_Vector; Item : Permutation);

   -- Helper function to get element at index from Permutation_Vector
   function Vector_Element (V : Permutation_Vector; Index : Positive) return Permutation
     with SPARK_Mode => On,
          Pre => Index > 0 and Index <= Integer(Vector_Capacity'Last) and Index <= Integer(V.Length);

   -- Helper procedure to clear a Permutation_Vector
   procedure Vector_Clear (V : in out Permutation_Vector);

end Permutations;
