------------------------------------------------------------------
--  Permutation Groups in Ada SPARK                              --
--  Implementation of Donald E. Knuth's algorithms Aₖ(π) and Bₖ(π) --
--  for computing strong generators and transversal systems        --
--                                                               --
--  File: permutations.ads                                        --
--  Description: Complete implementation with all algorithms       --
--  Version: 0.03                                               --
--                                                               --
--  Author: Vibe Code Agent                                       --
--  Date: 2024                                                   --
--  Reference: Knuth, D.E. "The Art of Computer Programming"     --
--             Volume 2, Section 4.6.3                            --
------------------------------------------------------------------

with Ada.Containers.Vectors;

package Permutations is
   pragma SPARK_Mode (On);

   -- Maximum size for permutations
   Max_Size : constant Positive := 100;

   -- Index type for permutations
   type Index is new Positive range 1 .. Max_Size;

   -- Permutation type: maps Index to Index
   type Permutation is array (Index) of Index;

   -- Identity permutation
   function Identity return Permutation
     with SPARK_Mode => On,
          Pre => True,
          Post => (for all I in Index => Identity'Result(I) = I);

   -- Permutation multiplication (composition): Left * Right
   function Multiply (Left, Right : Permutation) return Permutation
     with SPARK_Mode => On,
          Pre => (for all I in Index => Left(I) in Index and Right(I) in Index),
          Post => (for all I in Index => Multiply'Result(I) = Left(Right(I)));

   -- Permutation inverse
   function Inverse (P : Permutation) return Permutation
     with SPARK_Mode => On,
          Pre => True,
          Post => (for all I in Index => Inverse'Result(P(I)) = I and P(Inverse'Result(I)) = I);

   -- Check if a permutation is the identity
   function Is_Identity (P : Permutation) return Boolean
     with SPARK_Mode => On,
          Pre => True,
          Post => Is_Identity'Result = (for all I in Index => P(I) = I);

   -- Vector type for storing permutations
   package Perm_Vectors is new Ada.Containers.Vectors
     (Index => Positive, Element_Type => Permutation);
   use Perm_Vectors;

   -- Sigma type: array of vectors for each k and j
   type Sigma_Type is array (Index, Index) of Perm_Vectors.Vector;

   -- T type: array of vectors for strong generators at each level k
   type T_Type is array (Index) of Perm_Vectors.Vector;

   -- Check if permutation Pi is a member of the group generated by Sigma up to level K
   function Is_Member (Pi : Permutation; K : Index; Sigma : Sigma_Type) return Boolean
     with SPARK_Mode => On,
          Pre => K in Index and Pi'Length = Index'Length;

   -- Algorithm Aₖ(π): Appends a new permutation π to T(k)
   procedure Algorithm_A (K : Index; Pi : Permutation;
                         Sigma : in out Sigma_Type;
                         T : in out T_Type)
     with SPARK_Mode => On,
          Pre => K in Index and Pi'Length = Index'Length;

   -- Algorithm Bₖ(π): Ensures π is in Γ(k)
   procedure Algorithm_B (K : Index; Pi : Permutation;
                         Sigma : in out Sigma_Type;
                         T : in out T_Type)
     with SPARK_Mode => On,
          Pre => K > 1 and Pi'Length = Index'Length;

   -- Initialize the data structures
   procedure Initialize (N : Index; Sigma : out Sigma_Type; T : out T_Type)
     with SPARK_Mode => On,
          Pre => N in Index;

   -- Add a new generator to the group
   procedure Add_Generator (Pi : Permutation; Sigma : in out Sigma_Type; T : in out T_Type)
     with SPARK_Mode => On,
          Pre => Pi'Length = Index'Length;

   -- Compute the strong generating set for a given set of generators
   procedure Compute_Strong_Generators (Generators : Perm_Vectors.Vector;
                                        Sigma : out Sigma_Type;
                                        T : out T_Type)
     with SPARK_Mode => On,
          Pre => (for all I in 1 .. Perm_Vectors.Length(Generators) => 
                    Perm_Vectors.Element(Generators, I)'Length = Index'Length);

   -- Create a transposition (swap of two elements)
   function Create_Transposition (I, J : Index) return Permutation
     with SPARK_Mode => On,
          Pre => I in Index and J in Index;

   -- Maximum number of elements for cycle creation
   Max_Cycle_Size : constant Positive := Max_Size;
   
   -- Type for cycle elements
   type Cycle_Elements is array (Positive range 1 .. Max_Cycle_Size) of Index;
   
   -- Create a cycle permutation
   function Create_Cycle (Elements : Cycle_Elements; Length : Positive) return Permutation
     with SPARK_Mode => On,
          Pre => Length >= 2 and Length <= Max_Cycle_Size and
                (for all I in 1 .. Length => Elements(I) in Index);

   -- Check if two permutations are equal
   function "=" (Left, Right : Permutation) return Boolean
     with SPARK_Mode => On,
          Pre => True,
          Post => "="'Result = (for all I in Index => Left(I) = Right(I));

end Permutations;
