------------------------------------------------------------------
--  Permutation Groups in Ada SPARK                              --
--  Implementation of Donald E. Knuth's algorithms Aₖ(π) and Bₖ(π) --
--  for computing strong generators and transversal systems        --
--                                                               --
--  File: permutations.adb                                        --
--  Description: Complete implementation with all algorithms       --
--  Version: 0.07                                               --
--                                                               --
--  Author: Vibe Code Agent                                       --
--  Date: 2024                                                   --
--  Reference: Knuth, D.E. "The Art of Computer Programming"     --
--             Volume 2, Section 4.6.3                            --
------------------------------------------------------------------

package body Permutations is
   pragma SPARK_Mode (On);

   -- Helper function to get the length of a Permutation_Vector
   function Vector_Length (V : Permutation_Vector) return Vector_Capacity is
   begin
      return V.Length;
   end Vector_Length;

   -- Helper procedure to append to a Permutation_Vector
   procedure Vector_Append (V : in out Permutation_Vector; Item : Permutation) is
   begin
      if V.Length < Max_Vector_Size then
         V.Length := V.Length + 1;
         V.Data(V.Length) := Item;
      end if;
   end Vector_Append;

   -- Helper function to get element at index from Permutation_Vector
   function Vector_Element (V : Permutation_Vector; Index : Positive) return Permutation is
   begin
      return V.Data(Index);
   end Vector_Element;

   -- Helper procedure to clear a Permutation_Vector
   procedure Vector_Clear (V : in out Permutation_Vector) is
   begin
      V.Length := 0;
   end Vector_Clear;

   -- Identity permutation
   function Identity return Permutation is
   begin
      return Result : Permutation do
         for I in Index loop
            Result(I) := I;
         end loop;
      end return;
   end Identity;

   -- Permutation multiplication (composition)
   function Multiply (Left, Right : Permutation) return Permutation is
   begin
      return Result : Permutation do
         for I in Index loop
            Result(I) := Left(Right(I));
         end loop;
      end return;
   end Multiply;

   -- Permutation inverse
   function Inverse (P : Permutation) return Permutation is
   begin
      return Result : Permutation do
         for I in Index loop
            Result(P(I)) := I;
         end loop;
      end return;
   end Inverse;

   -- Check if a permutation is the identity
   function Is_Identity (P : Permutation) return Boolean is
   begin
      for I in Index loop
         if P(I) /= I then
            return False;
         end if;
      end loop;
      return True;
   end Is_Identity;

   -- Check if permutation Pi is a member of the group generated by Sigma up to level K
   function Is_Member (Pi : Permutation; K : Index; Sigma : Sigma_Type) return Boolean is
   begin
      if K = 1 then
         return True;
      end if;
      
      declare
         J : Index := Pi(K);
      begin
         -- If σₖⱼ is empty, Pi is not in the group
         if Vector_Length(Sigma(K, J)) = 0 then
            return False;
         end if;
         
         -- If K = 1, we're done (base case)
         if K = 1 then
            return True;
         end if;
         
         -- Recursively check if Pi * σₖⱼ⁻¹ is in Γ(k-1)
         declare
            Sigma_KJ : Permutation := Vector_Element(Sigma(K, J), 1);
            Sigma_KJ_Inv : Permutation := Inverse(Sigma_KJ);
            Pi_Transformed : Permutation := Multiply(Pi, Sigma_KJ_Inv);
         begin
            return Is_Member(Pi_Transformed, K-1, Sigma);
         end;
      end;
   end Is_Member;

   -- Algorithm Aₖ(π): Appends a new permutation π to T(k)
   procedure Algorithm_A (K : Index; Pi : Permutation;
                         Sigma : in out Sigma_Type;
                         T : in out T_Type) is
   begin
      -- Add Pi to T(K)
      Vector_Append(T(K), Pi);
      
      -- If K = 1, we're done (base case)
      if K = 1 then
         return;
      end if;
      
      -- For all σ ∈ Σ(k) and τ ∈ T(k), check if στ is not already in Γ(k)
      for J in Index loop
         if Vector_Length(Sigma(K, J)) > 0 then
            declare
               Sigma_KJ : Permutation := Vector_Element(Sigma(K, J), 1);
            begin
               -- For each τ in T(K)
               for Tau_Idx in 1 .. Integer(Vector_Length(T(K))) loop
                  declare
                     Tau : Permutation := Vector_Element(T(K), Tau_Idx);
                     Product : Permutation := Multiply(Sigma_KJ, Tau);
                  begin
                     -- Check if Product is not already in Γ(k)
                     if not Is_Member(Product, K, Sigma) then
                        -- Call Algorithm_B for this product
                        Algorithm_B(K, Product, Sigma, T);
                     end if;
                  end;
               end loop;
            end;
         end if;
      end loop;
      
      -- Also check products with the new Pi
      for Tau_Idx in 1 .. Integer(Vector_Length(T(K))) loop
         declare
            Tau : Permutation := Vector_Element(T(K), Tau_Idx);
            Product1 : Permutation := Multiply(Pi, Tau);
            Product2 : Permutation := Multiply(Tau, Pi);
         begin
            if not Is_Member(Product1, K, Sigma) then
               Algorithm_B(K, Product1, Sigma, T);
            end if;
            if not Is_Member(Product2, K, Sigma) then
               Algorithm_B(K, Product2, Sigma, T);
            end if;
         end;
      end loop;
   end Algorithm_A;

   -- Algorithm Bₖ(π): Ensures π is in Γ(k)
   procedure Algorithm_B (K : Index; Pi : Permutation;
                         Sigma : in out Sigma_Type;
                         T : in out T_Type) is
   begin
      -- Let π map k ↦ j
      declare
         J : Index := Pi(K);
      begin
         -- If σₖⱼ is empty, set σₖⱼ ← π and terminate
         if Vector_Length(Sigma(K, J)) = 0 then
            Vector_Append(Sigma(K, J), Pi);
            return;
         end if;
         
         -- If k = 1, we're done (base case)
         if K = 1 then
            return;
         end if;
         
         -- Check if πσₖⱼ⁻¹ ∈ Γ(k-1)
         declare
            Sigma_KJ : Permutation := Vector_Element(Sigma(K, J), 1);
            Sigma_KJ_Inv : Permutation := Inverse(Sigma_KJ);
            Pi_Transformed : Permutation := Multiply(Pi, Sigma_KJ_Inv);
         begin
            if Is_Member(Pi_Transformed, K-1, Sigma) then
               return; -- π is already in Γ(k), terminate
            else
               -- Otherwise, call Algorithm Aₖ₋₁(πσₖⱼ⁻¹)
               Algorithm_A(K-1, Pi_Transformed, Sigma, T);
               
               -- After adding new generators, we may need to update σₖⱼ
               if not Is_Member(Pi, K, Sigma) then
                  Vector_Clear(Sigma(K, J));
                  Vector_Append(Sigma(K, J), Pi);
               end if;
            end if;
         end;
      end;
   end Algorithm_B;

   -- Initialize the data structures for a given group size N
   procedure Initialize (N : Index; Sigma : out Sigma_Type; T : out T_Type) is
   begin
      -- Initialize all T(k) to empty vectors
      for K in Index loop
         Vector_Clear(T(K));
      end loop;
      
      -- Initialize all σₖⱼ to empty vectors
      for K in Index loop
         for J in Index loop
            Vector_Clear(Sigma(K, J));
         end loop;
      end loop;
   end Initialize;

   -- Add a new generator to the group
   procedure Add_Generator (Pi : Permutation; Sigma : in out Sigma_Type; T : in out T_Type) is
   begin
      -- Start with the highest level (Index'Last)
      Algorithm_B(Index'Last, Pi, Sigma, T);
   end Add_Generator;

   -- Compute the strong generating set for a given set of generators
   procedure Compute_Strong_Generators (Generators : Generator_Array;
                                        Sigma : out Sigma_Type;
                                        T : out T_Type) is
   begin
      -- Initialize the data structures
      Initialize(Index'Last, Sigma, T);
      
      -- Add each generator to the group
      for I in Generators'Range loop
         Add_Generator(Generators(I), Sigma, T);
      end loop;
   end Compute_Strong_Generators;

   -- Create a transposition (swap of two elements)
   function Create_Transposition (I, J : Index) return Permutation is
   begin
      return Result : Permutation := Identity do
         Result(I) := J;
         Result(J) := I;
      end return;
   end Create_Transposition;

   -- Create a cycle permutation
   function Create_Cycle (Elements : Cycle_Elements; Length : Positive) return Permutation is
   begin
      return Result : Permutation := Identity do
         -- Create the cycle: Elements(1) -> Elements(2) -> ... -> Elements(Length) -> Elements(1)
         for K in 1 .. Length - 1 loop
            Result(Elements(K)) := Elements(K + 1);
         end loop;
         Result(Elements(Length)) := Elements(1);
      end return;
   end Create_Cycle;

   -- Check if two permutations are equal
   function "=" (Left, Right : Permutation) return Boolean is
   begin
      for I in Index loop
         if Left(I) /= Right(I) then
            return False;
         end if;
      end loop;
      return True;
   end "=";

end Permutations;
