------------------------------------------------------------------
--  Permutation Groups in Ada SPARK                              --
--  Implementation of Donald E. Knuth's algorithms Aₖ(π) and Bₖ(π) --
--  for computing strong generators and transversal systems        --
--                                                               --
--  File: knuth_examples.adb                                     --
--  Description: Examples from Knuth's paper                     --
--                                                               --
--  Author: Vibe Code Agent                                       --
--  Date: 2024                                                   --
--  Reference: Knuth, D.E. "The Art of Computer Programming"     --
--             Volume 2, Section 4.6.3                            --
------------------------------------------------------------------

with Permutations;
with Sims_Algorithm;
with Utils;
with Ada.Text_IO;
use Permutations;
use Sims_Algorithm;
use Utils;
use Ada.Text_IO;

procedure Knuth_Examples is
   pragma SPARK_Mode (Off); -- Examples may use non-SPARK features for output

   -- Example data structures
   Sigma : Sigma_Type;
   T : T_Type;
   Generators : Perm_Vector;

begin
   Put_Line("=== KNUTH'S PERMUTATION GROUP EXAMPLES ===");
   New_Line;

   -- Example 1: Simple cyclic group
   Put_Line("Example 1: Cyclic group C_5 generated by (1 2 3 4 5)");
   
   -- Initialize
   Initialize(Index'Last, Sigma, T);
   Generators.Clear;
   
   -- Create the 5-cycle generator
   declare
      Cycle5 : Permutation := Create_Cycle((1, 2, 3, 4, 5));
   begin
      Generators.Append(new Permutation'(Cycle5));
      Add_Generator(Cycle5, Sigma, T);
      
      -- Test membership of various powers
      declare
         Cycle5_2 : Permutation := Multiply(Cycle5, Cycle5);
         Cycle5_3 : Permutation := Multiply(Cycle5_2, Cycle5);
         Cycle5_4 : Permutation := Multiply(Cycle5_3, Cycle5);
         Cycle5_5 : Permutation := Multiply(Cycle5_4, Cycle5); -- Should be identity
      begin
         Put_Line("  Generator: (1 2 3 4 5)");
         Put_Line("  (1 2 3 4 5)^2 in group: " & Boolean'Image(Is_Member(Cycle5_2, Index'Last, Sigma)));
         Put_Line("  (1 2 3 4 5)^3 in group: " & Boolean'Image(Is_Member(Cycle5_3, Index'Last, Sigma)));
         Put_Line("  (1 2 3 4 5)^4 in group: " & Boolean'Image(Is_Member(Cycle5_4, Index'Last, Sigma)));
         Put_Line("  (1 2 3 4 5)^5 = identity in group: " & Boolean'Image(Is_Member(Cycle5_5, Index'Last, Sigma)));
      end;
   end;
   
   New_Line;

   -- Example 2: Symmetric group S_3
   Put_Line("Example 2: Symmetric group S_3 generated by (1 2) and (2 3)");
   
   -- Initialize
   Initialize(Index'Last, Sigma, T);
   Generators.Clear;
   
   -- Create generators for S_3
   declare
      Trans12 : Permutation := Create_Transposition(1, 2);
      Trans23 : Permutation := Create_Transposition(2, 3);
   begin
      Generators.Append(new Permutation'(Trans12));
      Generators.Append(new Permutation'(Trans23));
      
      Add_Generator(Trans12, Sigma, T);
      Add_Generator(Trans23, Sigma, T);
      
      -- Test all elements of S_3
      declare
         Trans13 : Permutation := Multiply(Trans12, Multiply(Trans23, Trans12));
         Cycle123 : Permutation := Multiply(Trans12, Trans23);
         Cycle132 : Permutation := Multiply(Trans23, Trans12);
      begin
         Put_Line("  Generator (1 2) in group: " & Boolean'Image(Is_Member(Trans12, Index'Last, Sigma)));
         Put_Line("  Generator (2 3) in group: " & Boolean'Image(Is_Member(Trans23, Index'Last, Sigma)));
         Put_Line("  (1 3) = (1 2)(2 3)(1 2) in group: " & Boolean'Image(Is_Member(Trans13, Index'Last, Sigma)));
         Put_Line("  (1 2 3) = (1 2)(2 3) in group: " & Boolean'Image(Is_Member(Cycle123, Index'Last, Sigma)));
         Put_Line("  (1 3 2) = (2 3)(1 2) in group: " & Boolean'Image(Is_Member(Cycle132, Index'Last, Sigma)));
         Put_Line("  Identity in group: " & Boolean'Image(Is_Member(Identity, Index'Last, Sigma)));
      end;
   end;
   
   New_Line;

   -- Example 3: Dihedral group D_4 (symmetries of a square)
   Put_Line("Example 3: Dihedral group D_4 generated by r and s");
   Put_Line("  r = (1 2 3 4) - rotation by 90 degrees");
   Put_Line("  s = (2 4) - reflection");
   
   -- Initialize
   Initialize(Index'Last, Sigma, T);
   Generators.Clear;
   
   -- Create generators for D_4
   declare
      Rotation : Permutation := Create_Cycle((1, 2, 3, 4));
      Reflection : Permutation := Create_Transposition(2, 4);
   begin
      Generators.Append(new Permutation'(Rotation));
      Generators.Append(new Permutation'(Reflection));
      
      Add_Generator(Rotation, Sigma, T);
      Add_Generator(Reflection, Sigma, T);
      
      -- Test various elements of D_4
      declare
         Rotation2 : Permutation := Multiply(Rotation, Rotation); -- 180 degree rotation
         Rotation3 : Permutation := Multiply(Rotation2, Rotation); -- 270 degree rotation
         Reflection2 : Permutation := Multiply(Reflection, Rotation); -- Another reflection
      begin
         Put_Line("  Generator r = (1 2 3 4) in group: " & Boolean'Image(Is_Member(Rotation, Index'Last, Sigma)));
         Put_Line("  Generator s = (2 4) in group: " & Boolean'Image(Is_Member(Reflection, Index'Last, Sigma)));
         Put_Line("  r^2 = (1 3)(2 4) in group: " & Boolean'Image(Is_Member(Rotation2, Index'Last, Sigma)));
         Put_Line("  r^3 = (1 4 3 2) in group: " & Boolean'Image(Is_Member(Rotation3, Index'Last, Sigma)));
         Put_Line("  sr = (1 4)(2 3) in group: " & Boolean'Image(Is_Member(Reflection2, Index'Last, Sigma)));
         Put_Line("  Identity in group: " & Boolean'Image(Is_Member(Identity, Index'Last, Sigma)));
      end;
   end;
   
   New_Line;

   -- Example 4: Klein four-group
   Put_Line("Example 4: Klein four-group V_4 generated by (1 2)(3 4) and (1 3)(2 4)");
   
   -- Initialize
   Initialize(Index'Last, Sigma, T);
   Generators.Clear;
   
   -- Create generators for V_4
   declare
      Gen1 : Permutation := Identity;
      Gen2 : Permutation := Identity;
   begin
      -- (1 2)(3 4)
      Gen1(1) := 2; Gen1(2) := 1;
      Gen1(3) := 4; Gen1(4) := 3;
      
      -- (1 3)(2 4)
      Gen2(1) := 3; Gen2(3) := 1;
      Gen2(2) := 4; Gen2(4) := 2;
      
      Generators.Append(new Permutation'(Gen1));
      Generators.Append(new Permutation'(Gen2));
      
      Add_Generator(Gen1, Sigma, T);
      Add_Generator(Gen2, Sigma, T);
      
      -- Test all elements of V_4
      declare
         Gen3 : Permutation := Multiply(Gen1, Gen2); -- (1 4)(2 3)
      begin
         Put_Line("  Generator (1 2)(3 4) in group: " & Boolean'Image(Is_Member(Gen1, Index'Last, Sigma)));
         Put_Line("  Generator (1 3)(2 4) in group: " & Boolean'Image(Is_Member(Gen2, Index'Last, Sigma)));
         Put_Line("  (1 4)(2 3) = (1 2)(3 4) * (1 3)(2 4) in group: " & Boolean'Image(Is_Member(Gen3, Index'Last, Sigma)));
         Put_Line("  Identity in group: " & Boolean'Image(Is_Member(Identity, Index'Last, Sigma)));
         
         -- Verify that all non-identity elements have order 2
         Put_Line("  Order of (1 2)(3 4): " & Integer'Image(Permutation_Order(Gen1)));
         Put_Line("  Order of (1 3)(2 4): " & Integer'Image(Permutation_Order(Gen2)));
         Put_Line("  Order of (1 4)(2 3): " & Integer'Image(Permutation_Order(Gen3)));
      end;
   end;
   
   New_Line;

   -- Example 5: Demonstrate the strong generating set computation
   Put_Line("Example 5: Strong generating set computation");
   
   -- Initialize
   Initialize(Index'Last, Sigma, T);
   Generators.Clear;
   
   -- Create a set of generators
   declare
      Gen_A : Permutation := Create_Cycle((1, 2, 3));
      Gen_B : Permutation := Create_Transposition(1, 4);
   begin
      Generators.Append(new Permutation'(Gen_A));
      Generators.Append(new Permutation'(Gen_B));
      
      Put_Line("  Computing strong generating set for group generated by:");
      Put_Line("    (1 2 3) and (1 4)");
      
      Compute_Strong_Generators(Generators, Sigma, T);
      
      -- Display some information about the computed group
      Put_Line("  Strong generating set computed successfully");
      
      -- Count the number of strong generators at each level
      for K in 1 .. 6 loop
         if T(K).Length > 0 then
            Put_Line("  Level " & Integer'Image(K) & ": " & 
                     Integer'Image(T(K).Length) & " strong generators");
         end if;
      end loop;
      
      -- Test membership of some elements
      declare
         Test1 : Permutation := Multiply(Gen_A, Gen_B);
         Test2 : Permutation := Multiply(Gen_B, Gen_A);
         Test3 : Permutation := Multiply(Test1, Test2);
      begin
         Put_Line("  (1 2 3)(1 4) in group: " & Boolean'Image(Is_Member(Test1, Index'Last, Sigma)));
         Put_Line("  (1 4)(1 2 3) in group: " & Boolean'Image(Is_Member(Test2, Index'Last, Sigma)));
         Put_Line("  [(1 2 3)(1 4)][(1 4)(1 2 3)] in group: " & Boolean'Image(Is_Member(Test3, Index'Last, Sigma)));
      end;
   end;
   
   New_Line;
   Put_Line("=== EXAMPLES COMPLETED ===");

   -- Clean up
   Generators.Clear;
   for K in Index loop
      T(K).Clear;
      for J in Index loop
         Sigma(K, J).Clear;
      end loop;
   end loop;

exception
   when others =>
      Put_Line("Exception occurred during Knuth examples");

end Knuth_Examples;
