------------------------------------------------------------------
--  Permutation Groups in Ada SPARK                              --
--  Implementation of Donald E. Knuth's algorithms Aₖ(π) and Bₖ(π) --
--  for computing strong generators and transversal systems        --
--                                                               --
--  File: permutations.adb                                        --
--  Description: Permutation operations implementation            --
--  Version: 0.01                                               --
--                                                               --
--  Author: Vibe Code Agent                                       --
--  Date: 2024                                                   --
--  Reference: Knuth, D.E. "The Art of Computer Programming"     --
--             Volume 2, Section 4.6.3                            --
------------------------------------------------------------------

package body Permutations is
   pragma SPARK_Mode (On);

   -- Identity permutation
   function Identity return Permutation is
   begin
      return Result : Permutation do
         for I in Index loop
            Result(I) := I;
         end loop;
      end return;
   end Identity;

   -- Permutation multiplication (composition)
   function Multiply (Left, Right : Permutation) return Permutation is
   begin
      return Result : Permutation do
         for I in Index loop
            Result(I) := Left(Right(I));
         end loop;
      end return;
   end Multiply;

   -- Permutation inverse
   function Inverse (P : Permutation) return Permutation is
   begin
      return Result : Permutation do
         for I in Index loop
            Result(P(I)) := I;
         end loop;
      end return;
   end Inverse;

   -- Check if a permutation is the identity
   function Is_Identity (P : Permutation) return Boolean is
   begin
      for I in Index loop
         if P(I) /= I then
            return False;
         end if;
      end loop;
      return True;
   end Is_Identity;

   -- Check if permutation Pi is a member of the group generated by Sigma up to level K
   function Is_Member (Pi : Permutation; K : Index;
                      Sigma : Sigma_Type) return Boolean is
   begin
      if K = 1 then
         return True;
      end if;
      
      declare
         J : Index := Pi(K);
      begin
         -- If σₖⱼ is empty, Pi is not in the group
         if Sigma(K, J).Length = 0 then
            return False;
         end if;
         
         -- If K = 1, we're done (base case)
         if K = 1 then
            return True;
         end if;
         
         -- Recursively check if Pi * σₖⱼ⁻¹ is in Γ(k-1)
         declare
            Sigma_Inv : Permutation := Inverse(Sigma(K, J).Element(1).all);
            Pi_Transformed : Permutation := Multiply(Pi, Sigma_Inv);
         begin
            return Is_Member(Pi_Transformed, K-1, Sigma);
         end;
      end;
   end Is_Member;

   -- Get the image of element I under permutation P
   function Image (P : Permutation; I : Index) return Index is
   begin
      return P(I);
   end Image;

   -- Check if two permutations are equal
   function "=" (Left, Right : Permutation) return Boolean is
   begin
      for I in Index loop
         if Left(I) /= Right(I) then
            return False;
         end if;
      end loop;
      return True;
   end "=";

   -- Check if two permutations are different
   function "/=" (Left, Right : Permutation) return Boolean is
   begin
      return not (Left = Right);
   end "/=";

end Permutations;
