------------------------------------------------------------------
--  Permutation Groups in Ada SPARK                              --
--  Implementation of Donald E. Knuth's algorithms Aₖ(π) and Bₖ(π) --
--  for computing strong generators and transversal systems        --
--                                                               --
--  File: permutations.ads                                        --
--  Description: Permutation type and basic operations            --
--                                                               --
--  Author: Vibe Code Agent                                       --
--  Date: 2024                                                   --
--  Reference: Knuth, D.E. "The Art of Computer Programming"     --
--             Volume 2, Section 4.6.3                            --
------------------------------------------------------------------

with Ada.Containers.Vectors;

package Permutations is
   pragma SPARK_Mode (On);

   -- Maximum size for permutations (can be adjusted as needed)
   Max_Size : constant Positive := 100;

   -- Index type for permutations
   type Index is new Positive range 1 .. Max_Size;

   -- Permutation type: maps Index to Index
   type Permutation is array (Index) of Index;

   -- Identity permutation
   function Identity return Permutation
     with SPARK_Mode => On,
          Post => (for all I in Index => Identity'Result(I) = I);

   -- Permutation multiplication (composition): Left * Right
   -- Result[I] = Left[Right[I]]
   function Multiply (Left, Right : Permutation) return Permutation
     with SPARK_Mode => On,
          Pre => (for all I in Index => Left(I) in Index and Right(I) in Index),
          Post => (for all I in Index => 
                     Multiply'Result(I) = Left(Right(I)));

   -- Permutation inverse
   function Inverse (P : Permutation) return Permutation
     with SPARK_Mode => On,
          Post => (for all I in Index => 
                     Inverse'Result(P(I)) = I and P(Inverse'Result(I)) = I);

   -- Check if a permutation is the identity
   function Is_Identity (P : Permutation) return Boolean
     with SPARK_Mode => On,
          Post => Is_Identity'Result = (for all I in Index => P(I) = I);

   -- Vector type for storing permutations
   type Perm_Vector is new Ada.Containers.Vectors.Vector
     with private;

   -- Access type for permutation elements in vectors
   type Element_Access is access all Permutation;

   -- Sigma type: array of permutation vectors for each k and j
   -- σₖⱼ represents the transversal element that maps k to j
   type Sigma_Type is array (Index, Index) of Perm_Vector;

   -- T type: array of permutation vectors for strong generators at each level k
   type T_Type is array (Index) of Perm_Vector;

   -- Check if permutation Pi is a member of the group generated by Sigma up to level K
   -- This implements the membership test from Knuth's algorithm
   function Is_Member (Pi : Permutation; K : Index;
                      Sigma : Sigma_Type) return Boolean
     with SPARK_Mode => On,
          Pre => K in Index and Pi'Length = Index'Length,
          Post => Is_Member'Result = 
                 (if K = 1 then True
                  else (let J := Pi(K); 
                        Sigma(K, J).Length > 0 and then
                        (if K = 1 then True
                         else Is_Member(Multiply(Pi, Inverse(Sigma(K, J).Element(1).all)), K-1, Sigma))));

   -- Get the image of element I under permutation P
   function Image (P : Permutation; I : Index) return Index
     with SPARK_Mode => On,
          Pre => I in Index,
          Post => Image'Result = P(I);

   -- Check if two permutations are equal
   function "=" (Left, Right : Permutation) return Boolean
     with SPARK_Mode => On,
          Post => "="'Result = (for all I in Index => Left(I) = Right(I));

   -- Check if two permutations are different
   function "/=" (Left, Right : Permutation) return Boolean
     with SPARK_Mode => On,
          Post => "/="'Result = not (Left = Right);

private
   pragma SPARK_Mode (On);

   -- Private implementation of Perm_Vector
   type Perm_Vector is new Ada.Containers.Vectors.Vector
     with type Element_Type is Element_Access;

end Permutations;
