------------------------------------------------------------------
--  Permutation Groups in Ada SPARK                              --
--  Implementation of Donald E. Knuth's algorithms Aₖ(π) and Bₖ(π) --
--  for computing strong generators and transversal systems        --
--                                                               --
--  File: sims_algorithm.ads                                      --
--  Description: Sims' algorithm for permutation groups            --
--  Version: 0.02                                               --
--                                                               --
--  Author: Vibe Code Agent                                       --
--  Date: 2024                                                   --
--  Reference: Knuth, D.E. "The Art of Computer Programming"     --
--             Volume 2, Section 4.6.3                            --
------------------------------------------------------------------

with Permutations;
use Permutations;

package Sims_Algorithm is
   pragma SPARK_Mode (On);

   -- Algorithm Aₖ(π): Appends a new permutation π to T(k)
   -- Ensures the data structure remains up-to-date so that Γ(k) equals 
   -- the new group generated by T(k)
   -- Calls Algorithm Bₖ(στ) for all σ ∈ Σ(k) and τ ∈ T(k) where στ is not already in Γ(k)
   procedure Algorithm_A (K : Index; Pi : Permutation;
                         Sigma : in out Sigma_Type;
                         T : in out T_Type)
     with SPARK_Mode => On,
          Pre => K in Index and Pi'Length = Index'Length;

   -- Algorithm Bₖ(π): Ensures π is in Γ(k) and the data structure remains 
   -- up-to-date of order k-1
   -- Steps:
   --   Let π map k ↦ j.
   --   If σₖⱼ is empty, set σₖⱼ ← π and terminate.
   --   If πσₖⱼ⁻¹ ∈ Γ(k-1), terminate.
   --   Otherwise, call Algorithm Aₖ₋₁(πσₖⱼ⁻¹).
   procedure Algorithm_B (K : Index; Pi : Permutation;
                         Sigma : in out Sigma_Type;
                         T : in out T_Type)
     with SPARK_Mode => On,
          Pre => K > 1 and Pi'Length = Index'Length;

   -- Initialize the data structures for a given group size N
   procedure Initialize (N : Index;
                        Sigma : out Sigma_Type;
                        T : out T_Type)
     with SPARK_Mode => On,
          Pre => N in Index;

   -- Add a new generator to the group
   procedure Add_Generator (Pi : Permutation;
                           Sigma : in out Sigma_Type;
                           T : in out T_Type)
     with SPARK_Mode => On,
          Pre => Pi'Length = Index'Length;

   -- Compute the strong generating set for a given set of generators
   procedure Compute_Strong_Generators (Generators : Perm_Vector;
                                        Sigma : out Sigma_Type;
                                        T : out T_Type)
     with SPARK_Mode => On,
          Pre => (for all I in 1 .. Generators.Length => 
                    Generators.Element(I).all'Length = Index'Length);

end Sims_Algorithm;
